name: conda-open-ce-PTL


channels:
  # - https://ftp.osuosl.org/pub/open-ce/current/
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch-cuda=11.7
  - torchvision
  - pip
  - pip:
      - azureml-mlflow
      - centernet2
      - 'git+https://github.com/facebookresearch/detectron2.git'
      - clip-anytorch
      - evaluate
      - ftfy
      - future
      - ipykernel
      - matplotlib
      - matplotlib-inline==0.1.6
      - mlflow
      - numpy==1.23.3
      - openpyxl
      - pytorch-lightning
      - pysmartdl
      - scikit-learn==1.2.1
      - scipy==1.9.3
      - setuptools==59.5.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - test_tube
      - timm
      - transformers
      - torch-cka
      - wget 