FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
WORKDIR /app
COPY . /app

EXPOSE 5000/tcp

ENTRYPOINT ["python", "app.py"]