FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
RUN pip install --upgrade pip
RUN pip install scipy
WORKDIR /app
# COPY . /app needs to follow symlinks too
COPY . /app

# show the files in the container
RUN ls -la /app
EXPOSE 5000/tcp

ENTRYPOINT ["python", "app.py"]