version: "3"
services:
  lsavis:
    image: st7ma784/lsavis:latest
    container_name: lsavis
    # network-mode: host
    # map to 5000
    ports:
      - 5001:5000
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 demo lsavis
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always


  demo: 
    image: st7ma784/vis:latest
    container_name: demo
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
    # open port 5001 on host to port 5000 
      - "5000:5000"

# create nginx container
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - lsavis
      - demo
    environment:
      - lsa_server_addr=lsavis:5000/lsa
      - demo_server_addr=demo:5000/demo 
    ports:
    # open port 80 on host to port 80 
      - "8081:80"
    volumes:
    # mount nginx config file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - lsavis
      - demo